---

dist: xenial

sudo: required

language: java

env:
# switch to openjdk:
#- JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

# switch to oracle:
jdk:
- oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
    - ls -lthra
# switch to openjdk:
#    - sudo add-apt-repository -y ppa:openjdk-r/ppa
#    - sudo apt-get -qq update
#    - sudo apt-get install -y openjdk-8-jdk --no-install-recommends
#    - sudo apt-get install -y openjfx
#    - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
    - java -version
    - echo "starting build..."

install:
  - java -version
  - ./build-coatjava.sh

script:
  - ls -lthra
  - which groovy
  - echo "starting advanced tests..."
  - cd validation/advanced-tests/
  - ./run-advanced-tests.sh
  - ./run-eb-tests.sh -100 electronproton
  - ./run-eb-tests.sh -100 electrongamma
  - ./run-eb-tests.sh -100 electronprotonC
  - ./run-eb-tests.sh -100 electronneutronC
  - cd -
  - echo "finished advanced tests"
  - mvn cobertura:cobertura &> /dev/null # for codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  emails: false
